services:

  cron:
    build:
      dockerfile: Dockerfile
      target: cron
    volumes:
    - "./config.json:/app/config.json"

  web:
    build:
      dockerfile: Dockerfile
      target: web
    volumes:
      - ./config.json:/var/www/reon/config.json:ro

  nginx:
    image: nginx:1.27.0
    volumes:
      - ./examples/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./web/:/var/www/reon/web
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
      - NGINX_HOST="_"
      # Hostname and port for fastcgi_pass directive
      - WEB_URL=web:9000

  mail:
    build:
      dockerfile: Dockerfile
      target: mail
    ports:
      - 25:25
      - 110:110
    volumes:
      - ./config.json:/app/config.json:ro

  db:
    image: mysql:8.4.0
    ports:
      - 3306:3306
    volumes:
      # Run tables.sql on startup
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql:ro
      - reon_db:/var/lib/mysql
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD

  dns:
    build:
      dockerfile: Dockerfile
      target: dns
    ports:
      - 53:53/udp
    environment:
      - EXTERNAL_IP

volumes:
  reon_db:
    name: reon_db